services:
  app:
    image: ${APP_IMAGE:-local/app}
    environment:
      - ERE_DB_URL=jdbc:mariadb://mariadb:3306/ere
      - ERE_DB_USER=ere
      - ERE_DB_PASS=${APP_DB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - app-network
  mariadb:
    image: mariadb:11.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ere
      - MYSQL_USER=ere
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always
    networks:
      - app-network
volumes:
  mariadb_data:
networks:
  app-network:
    driver: bridge
